name: daily-report

on:
  schedule:
    - cron: '0 7,15,23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo content
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12.3'
        - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: '22.11.0'
        - name: update system
          run: |
              sudo apt update && sudo apt install -y \
              libwoff1 libvpx7 libevent-2.1-7 libopus0 \
              libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 \
              libharfbuzz-icu0 libhyphen0 libmanette-0.2-0 \
              flite libgles2-mesa
        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            - name: install browsers
        - run: |
              playwright install
        - name: Run code
          env: 
            PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
          run: python main.py
